name: Gerar oferta

on:
  workflow_dispatch:

jobs:
  gerar:
    runs-on: windows-latest

    steps:

      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Testar gerador
        shell: pwsh
        run: |
          Write-Host "Gerador encontrado:"
          Test-Path ".\gerador\gerar-oferta.ps1"

          Write-Host ""
          Write-Host "Arquivos do gerador:"
          Get-ChildItem ".\gerador"